# Generated by Django 5.1.3 on 2025-02-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_available_copies_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
