# Generated by Django 5.1.3 on 2025-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_staffactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='max_books_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
