# Generated by Django 5.1.3 on 2025-02-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_staffmember_timestamp_alter_member_max_books_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='max_books_allowed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
