# Generated by Django 5.1.3 on 2025-02-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_alter_member_max_books_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='max_books_allowed',
            field=models.PositiveIntegerField(),
        ),
    ]
